### PR TITLE
proper use of pg-promise

### PR DESCRIPTION
**Pull request by vitaly-t**
1. use a transaction to do bulk changes;
2. use `batch` when executing independent queries;
3. correctly chain results from promises.
4. Use query methods that correctly represent the expected result.

### CODE REVIEW

**Comment by vitaly-t** [comment]
Couple corrections:

``` js
db.tx(t=> t.one(sql.test)
    .then(data=> !!data.exists || t.batch([
            t.none(sql.drop),
            t.none(sql.build)
        ])
        .then(()=>false))
    )
    .then(rebuilt=> {
        if (rebuilt) {
            console.log('Database was rebuilt.');
        } else {
            console.log('Users table already exists.');
        }
    })
    .catch(error=> {
        console.log("ERROR:", error);
    })
    .finally(pgp.end);
```

**Comment by alexnitta** [comment]
@vitaly-t - wow, I wasn't expecting to get help from the author of pg-promise. This is very helpful! Thanks!

**Comment by alexnitta** [comment]
This is behaving as expected, but I'm seeing this in the server console: 
```
Unhandled rejection (<[{"success":false,"result":"Loose requ...>, no stack trace)
```
This seems to be related to a promise that wasn't given a `catch`, but when I add one to `t.one` it causes another error. Any thoughts on this?

**Comment by vitaly-t** [comment]
> This is behaving as expected, but I'm seeing this in the server console:
> Unhandled rejection (<[{"success":false,"result":"Loose requ...>, no stack trace)
> This seems to be related to a promise that wasn't given a catch, but when I add one to t.one it causes another error. Any thoughts on this?

Unhandled rejection - yes, that's when you are missing `.catch`.

As for error `Loose request outside an expired connection.` - that's when executing queries inside a task or transaction without properly chaining them. Check out this: https://github.com/vitaly-t/pg-promise/issues/120

Did you apply the update I posted right after? I missed a `return` there initially, which would have resulted in that error.

**Comment by alexnitta** [comment]
After I posted that comment, I saw your update, which fixed the error. I deleted the comment but should have just written another one - sorry about that. I'm new to ES6 so I was also having trouble reasoning about the arrow function. I refactored it like this, which is working great:

``` javascript
db.tx(t=> t.one(sql.test)
  .then((data) => {
    // if users table doesn't exist, rebuild database
    if (!data.exists) {
      console.log('Rebuilding database');
      t.batch([t.none(sql.drop), t.none(sql.build)]);
    } else {
      console.log('Users table exists, not rebuilding database');
    }
  })
  .catch(error=> {
    console.log('error:', error);
  })
  .finally(pgp.end)
);
```

**Comment by vitaly-t** [comment]
That's not a valid code, you refactored it wrong, I'm afraid, because your are not chaining the call into `t.batch`, it will result again in a `Loose request outside an expired connection.` on a race condition.

Change it to:

``` js
db.tx(t=> t.one(sql.test)
  .then((data) => {
    // if users table doesn't exist, rebuild database
    if (!data.exists) {
      console.log('Rebuilding database');
      return t.batch([t.none(sql.drop), t.none(sql.build)]);
    } else {
      console.log('Users table exists, not rebuilding database');
    }
  })
  .catch(error=> {
    console.log('error:', error);
  })
  .finally(pgp.end)
);
```

You cannot create promises and not chain them ;) And `batch` returns a new promise.

**Comment by alexnitta** [comment]
> batch returns a new promise.

Ah, got it. Thanks!

**Pull request merged**
